#T. Martz-Oberlander, 2015-11-13
#Makefile for organ pitch project

# all : [files]

#upload_pitch_data.py #to wrangle pitch datafiles 
#upload_env_data.py #to warngle environmental datafiles

# make figure, save figure

#clean (Delete files made)

clean :
	pitch.csv
	#fig 


